// db_insert.js
import pg from 'pg';
import { generateDatabasePayload } from './orchestrator.js';
import { fileURLToPath } from 'url';

const { Pool } = pg;

// Initialize PostgreSQL connection pool
const pool = new Pool({
    user: process.env.DB_USER || 'postgres',
    host: process.env.DB_HOST || 'localhost',
    database: process.env.DB_NAME || 'Cyclone',
    password: process.env.DB_PASSWORD || 'user123',
    port: process.env.DB_PORT || 5432,
});

/**
 * Inserts or updates the cyclone payload into the PostgreSQL database.
 * Uses a transaction to ensure data integrity across both tables.
 * 
 * @param {Object} payload - The JSON object generated by orchestrator.js
 */
export async function insertDataIntoDb(payload) {
    const client = await pool.connect();

    try {
        // Start database transaction
        await client.query('BEGIN');
        
        let cycloneId;

        // 1. Check if an active/developing cyclone already exists in this region
        const checkExistingQuery = `
            SELECT id FROM cyclones 
            WHERE region = $1
            ORDER BY formation_date DESC LIMIT 1;
        `;
        const existingResult = await client.query(checkExistingQuery, [payload.cyclone.region]);

        if (existingResult.rows.length > 0) {
            // Update the existing cyclone with the latest meteorological data
            cycloneId = existingResult.rows[0].id;
            
            const updateCycloneQuery = `
                UPDATE cyclones 
                SET wind_speed = $1, 
                    central_pressure = $2, 
                    destructive_scale = $3, 
                    status = $4,
                    classification = $6
                WHERE id = $5;
            `;
            await client.query(updateCycloneQuery, [
                payload.cyclone.wind_speed,
                payload.cyclone.central_pressure,
                payload.cyclone.destructive_scale,
                payload.cyclone.status,
                cycloneId,
                payload.cyclone.classification
            ]);
            console.log(`Updated existing cyclone (ID: ${cycloneId}) with latest telemetry.`);
            
        } else {
            // Insert a completely new cyclone record
            const insertCycloneQuery = `
                INSERT INTO cyclones (name, wind_speed, central_pressure, destructive_scale, status, formation_date, region, classification)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                RETURNING id;
            `;
            const insertResult = await client.query(insertCycloneQuery, [
                payload.cyclone.name,
                payload.cyclone.wind_speed,
                payload.cyclone.central_pressure,
                payload.cyclone.destructive_scale,
                payload.cyclone.status,
                payload.cyclone.formation_date,
                payload.cyclone.region,
                payload.cyclone.classification
            ]);
            
            cycloneId = insertResult.rows[0].id;
            console.log(`Created new cyclone record (ID: ${cycloneId}).`);
        }

        // 2. Insert the tracking data point with full telemetry snapshot
        const insertTrackingQuery = `
            INSERT INTO cyclone_tracking (
                cyclone_id, recorded_at, latitude, longitude, record_type, 
                wind_speed, central_pressure, destructive_scale, status, classification
            )
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10);
        `;
        
        const trackingResult = await client.query(insertTrackingQuery, [
            cycloneId,
            payload.tracking.recorded_at,
            payload.tracking.latitude,
            payload.tracking.longitude,
            payload.tracking.record_type,
            payload.cyclone.wind_speed,         // Snapshot metric
            payload.cyclone.central_pressure,   // Snapshot metric
            payload.cyclone.destructive_scale,  // Snapshot metric
            payload.cyclone.status,             // Snapshot metric
            payload.cyclone.classification      // Snapshot metric
        ]);

        if (trackingResult.rowCount === 0) {
            console.log(`Tracking data for ${payload.tracking.recorded_at} already exists. Skipped duplicate.`);
        } else {
            console.log(`Successfully added tracking coordinates: [${payload.tracking.latitude}°, ${payload.tracking.longitude}°].`);
        }

        // Commit transaction
        await client.query('COMMIT');
        console.log("Database insertion pipeline completed successfully.");

    } catch (error) {
        // Rollback all changes if any query fails
        await client.query('ROLLBACK');
        console.error("Database Transaction Failed. Rolled back changes:", error.message);
        throw error;
    } finally {
        // Release the client back to the pool
        client.release();
    }
}

/**
 * Helper function to run the full pipeline from an image path
 */
async function processImageAndInsert(imagePath) {
    try {
        console.log(`Processing image: ${imagePath}`);
        const payload = await generateDatabasePayload(imagePath);
        
        console.log("Generated Payload:", JSON.stringify(payload, null, 2));
        
        await insertDataIntoDb(payload);
    } catch (error) {
        console.error("Pipeline execution stopped:", error.message);
    } finally {
        // Close the database pool so the Node process can exit
        await pool.end();
    }
}

// Execute the script directly if an image path is passed via CLI
// Example: node db_insert.js "C:/Users/.../frame_0000.png"
if (process.argv[1] === fileURLToPath(import.meta.url) || process.argv[1].endsWith('db_insert.js')) {
     // Ensure CLI execution detection works in ES modules
    const imageInput = process.argv[2];
    
    if (!imageInput) {
        console.error("Error: Please provide an image path as a CLI argument.");
        process.exit(1);
    }
    
    processImageAndInsert(imageInput);
}